//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstFloor.ModernUI.App.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lanteria.effectivestaff.wsp")]
        public string CoreSolution {
            get {
                return ((string)(this["CoreSolution"]));
            }
            set {
                this["CoreSolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lanteria.ES.SharePoint_LanteriaSite")]
        public string SiteFeature {
            get {
                return ((string)(this["SiteFeature"]));
            }
            set {
                this["SiteFeature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lanteria.ES.SharePoint_LanteriaWeb")]
        public string WebFeature {
            get {
                return ((string)(this["WebFeature"]));
            }
            set {
                this["WebFeature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lanteria.ES.SharePoint_LanteriaContent")]
        public string ContentFeature {
            get {
                return ((string)(this["ContentFeature"]));
            }
            set {
                this["ContentFeature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lanteria.ES.SharePoint_lanteriaSQL")]
        public string SqlFeature {
            get {
                return ((string)(this["SqlFeature"]));
            }
            set {
                this["SqlFeature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lanteria.ES.SharePoint_LanteriaADIntergation")]
        public string ADFeature {
            get {
                return ((string)(this["ADFeature"]));
            }
            set {
                this["ADFeature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lanteria.ES.SharePoint_LanteriaUserProfileIntegration")]
        public string UPFeature {
            get {
                return ((string)(this["UPFeature"]));
            }
            set {
                this["UPFeature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a5fd7f06-6bbc-4f25-9192-cff892ce5e9b")]
        public global::System.Guid SolutionID {
            get {
                return ((global::System.Guid)(this["SolutionID"]));
            }
            set {
                this["SolutionID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\lanteria\\update\\")]
        public string Path {
            get {
                return ((string)(this["Path"]));
            }
            set {
                this["Path"] = value;
            }
        }
    }
}
